// RESHA — Reverence in Recycling
// Circular infrastructure for sacred ritual textile waste

export const NETWORK_NODES = [
  {
    id: 'varanasi',
    name: 'Kashi Vishwanath Temple Trust',
    lat: 25.3176,
    lng: 82.9739,
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    type: 'active',
    institution_type: 'Hindu Temple | Tier-1 Heritage Site',
    status: 'Active Pilot',
    installed: 'January 2025',
    shredder: 'MS-007',
    capacity: '80kg/day',
    waste_diverted: 2340,
    last_pickup: 'April 18, 2025',
    partner: 'EcoFiber Pvt. Ltd., Kanpur',
    batches: 'RSH-2024-VNS-0141 through 0151',
  },
  {
    id: 'amritsar',
    name: 'Shri Harmandir Sahib (Golden Temple)',
    lat: 31.6200,
    lng: 74.8765,
    city: 'Amritsar',
    state: 'Punjab',
    type: 'active',
    institution_type: 'Gurudwara | Tier-1 Heritage Site',
    status: 'Active Pilot',
    installed: 'February 2025',
    shredder: 'MS-011',
    capacity: '80kg/day',
    waste_diverted: 1980,
    last_pickup: 'April 20, 2025',
    partner: 'GreenWeave Industries, Ludhiana',
    batches: 'RSH-2025-AMR-0021 through 0028',
  },
  {
    id: 'tirupati',
    name: 'Tirumala Tirupati Devasthanam',
    lat: 13.6288,
    lng: 79.4192,
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    type: 'active',
    institution_type: 'Hindu Temple | National Religious Site',
    status: 'Active Pilot',
    installed: 'March 2025',
    shredder: 'MS-014',
    capacity: '80kg/day',
    waste_diverted: 1640,
    last_pickup: 'April 15, 2025',
    partner: 'SouthFiber Recyclers, Coimbatore',
    batches: 'RSH-2025-TPT-0009 through 0015',
  },
  {
    id: 'jaipur',
    name: 'Govind Dev Ji Temple Trust',
    lat: 26.9124,
    lng: 75.7873,
    city: 'Jaipur',
    state: 'Rajasthan',
    type: 'active',
    institution_type: 'Hindu Temple | State Heritage',
    status: 'Active Pilot',
    installed: 'March 2025',
    shredder: 'MS-018',
    capacity: '80kg/day',
    waste_diverted: 890,
    last_pickup: 'April 22, 2025',
    partner: 'RajFiber Solutions, Bhilwara',
    batches: 'RSH-2025-JPR-0001 through 0006',
  },
  {
    id: 'kanpur',
    name: 'EcoFiber Pvt. Ltd.',
    lat: 26.4499,
    lng: 80.3319,
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    type: 'partner',
    institution_type: 'Certified Processing Partner',
    status: 'Processing Partner',
    installed: 'December 2024',
    shredder: null,
    capacity: '500kg/day',
    waste_diverted: 4200,
    last_pickup: 'April 23, 2025',
    partner: null,
    batches: null,
  },
  {
    id: 'surat',
    name: 'TextileRevive Labs',
    lat: 21.1702,
    lng: 72.8311,
    city: 'Surat',
    state: 'Gujarat',
    type: 'partner',
    institution_type: 'Certified Processing Partner',
    status: 'Processing Partner',
    installed: 'January 2025',
    shredder: null,
    capacity: '400kg/day',
    waste_diverted: 3800,
    last_pickup: 'April 21, 2025',
    partner: null,
    batches: null,
  },
  {
    id: 'mumbai',
    name: 'ISKCON Mumbai',
    lat: 19.0760,
    lng: 72.8777,
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'onboarding',
    institution_type: 'Hindu Temple | ISKCON Chapter',
    status: 'Onboarding in Progress',
    installed: null,
    shredder: null,
    capacity: null,
    waste_diverted: 0,
    last_pickup: null,
    partner: null,
    batches: null,
  },
  {
    id: 'kolkata',
    name: 'Dakshineswar Kali Temple',
    lat: 22.5557,
    lng: 88.3639,
    city: 'Kolkata',
    state: 'West Bengal',
    type: 'onboarding',
    institution_type: 'Hindu Temple | Heritage Site',
    status: 'Onboarding in Progress',
    installed: null,
    shredder: null,
    capacity: null,
    waste_diverted: 0,
    last_pickup: null,
    partner: null,
    batches: null,
  },
  {
    id: 'pune',
    name: 'Aga Khan Palace Trust',
    lat: 18.5204,
    lng: 73.8567,
    city: 'Pune',
    state: 'Maharashtra',
    type: 'onboarding',
    institution_type: 'Multi-faith Institution',
    status: 'Onboarding in Progress',
    installed: null,
    shredder: null,
    capacity: null,
    waste_diverted: 0,
    last_pickup: null,
    partner: null,
    batches: null,
  },
];

export const NETWORK_METRICS = [
  { label: 'Ritual Textile Waste Diverted', value: 12400, suffix: ' kg', icon: 'Leaf' },
  { label: 'Active Pilot Sites', value: 8, suffix: '', icon: 'MapPin' },
  { label: 'Institutions Onboarded', value: 23, suffix: '', icon: 'Building' },
  { label: 'Certified Processing Partners', value: 5, suffix: '', icon: 'Shield' },
  { label: 'States Covered', value: 3, suffix: '', icon: 'Map' },
  { label: 'CO₂ Equivalent Prevented', value: 410, suffix: ' kg', icon: 'Wind' },
];

export const RECENT_ACTIVITIES = [
  {
    id: 1,
    icon: 'Check',
    text: 'Batch RSH-VNS-0151 certified',
    detail: 'Kashi Vishwanath Temple Trust, Varanasi',
    timestamp: '2 hours ago',
  },
  {
    id: 2,
    icon: 'Refresh',
    text: 'Pickup completed',
    detail: 'Golden Temple, Amritsar',
    timestamp: '1 day ago',
  },
  {
    id: 3,
    icon: 'Clipboard',
    text: 'New onboarding request',
    detail: 'ISKCON Mumbai — pending review',
    timestamp: '2 days ago',
  },
  {
    id: 4,
    icon: 'Settings',
    text: 'Shredder MS-014 installed',
    detail: 'Tirupati Devasthanam, Tirupati',
    timestamp: '5 days ago',
  },
  {
    id: 5,
    icon: 'Package',
    text: 'EcoFiber received 340 kg batch',
    detail: 'Processed → recycled cotton fiber',
    timestamp: '6 days ago',
  },
  {
    id: 6,
    icon: 'Leaf',
    text: 'ESG report published',
    detail: 'Q1 2025 — 12,400 kg diverted',
    timestamp: '1 week ago',
  },
];

export const PROCESSING_BATCHES = [
  {
    id: 'RSH-2024-VNS-0147',
    source: 'Kashi Vishwanath Temple Trust, Varanasi',
    date: '12 April 2025',
    weight: '34.2 kg',
    partner: 'EcoFiber Pvt. Ltd., Kanpur',
    output: 'Recycled cotton fiber',
    status: 'Delivered & Certified',
    status_type: 'completed',
  },
  {
    id: 'RSH-2025-AMR-0026',
    source: 'Shri Harmandir Sahib, Amritsar',
    date: '18 April 2025',
    weight: '28.7 kg',
    partner: 'GreenWeave Industries, Ludhiana',
    output: 'Blended yarn fiber',
    status: 'Processing',
    status_type: 'processing',
  },
  {
    id: 'RSH-2025-TPT-0013',
    source: 'Tirumala Tirupati Devasthanam',
    date: '20 April 2025',
    weight: '51.3 kg',
    partner: 'SouthFiber Recyclers, Coimbatore',
    output: 'Cotton rags for industry',
    status: 'Delivered & Certified',
    status_type: 'completed',
  },
  {
    id: 'RSH-2025-JPR-0005',
    source: 'Govind Dev Ji Temple Trust, Jaipur',
    date: '22 April 2025',
    weight: '19.8 kg',
    partner: 'RajFiber Solutions, Bhilwara',
    output: 'Recycled textile fiber',
    status: 'In Transit',
    status_type: 'transit',
  },
  {
    id: 'RSH-2025-AMR-0028',
    source: 'Shri Harmandir Sahib, Amritsar',
    date: '24 April 2025',
    weight: '33.1 kg',
    partner: 'GreenWeave Industries, Ludhiana',
    output: 'Pending processing',
    status: 'Collected',
    status_type: 'collected',
  },
];

export const HOME_SECTIONS = {
  hero: {
    headline_line1: 'Sacred Cloth.',
    headline_line2: 'Reborn with Reverence.',
    subheadline: "India's first dignity-first circular infrastructure for ritual textile waste — from temple floors to recycled fiber.",
    cta_primary: 'Explore Network →',
    cta_secondary: 'Partner With RESHA →',
  },
  problem: {
    title: 'The Holy Waste Paradox',
    description: 'Devotees across India cannot discard sacred cloth in ordinary bins — it is a spiritual crisis, not just an environmental one. The sanctity of offerings demands a dignified, consecrated path to transformation.',
    stats: [
      { number: '800M+', label: 'Tonnes of ritual offerings generated annually across India' },
      { number: '7.79M', label: 'Tonnes of India\'s annual unmanaged textile waste' },
      { number: '3.4%', label: 'Cloth waste share at major temple sites like Thirunallar' },
    ],
    cards: [
      {
        icon: 'Hands',
        title: 'Cultural Dilemma',
        description: 'Sacred offerings — silks, cotton, marigold-dyed cloth — cannot be discarded in ordinary waste streams without violating religious sanctity.',
      },
      {
        icon: 'BarChart',
        title: 'Scale of Crisis',
        description: 'Tens of millions of devotees generate ritual textile waste daily. Temples lack infrastructure for dignified, systematic disposal.',
      },
      {
        icon: 'Sprout',
        title: 'Ecological Consequence',
        description: 'Ritual cloth immersed in rivers or burned openly creates water contamination, dye pollution, and unmanaged textile landfill.',
      },
    ],
  },
  solution: {
    title: 'The Dignity-First Approach',
    steps: [
      {
        icon: 'Temple',
        name: 'Institution',
        description: 'Temple or religious institution generates ritual textile waste from daily offerings and ceremonies.',
      },
      {
        icon: 'Package',
        name: 'Collection',
        description: 'Dedicated, consecrated collection point established on-site with sacred vessel branding.',
      },
      {
        icon: 'Settings',
        name: 'Moksha Shredder',
        description: 'On-premise shredding processes cloth within consecrated grounds — fabric never leaves as intact.',
      },
      {
        icon: 'Refresh',
        name: 'Processing',
        description: 'Shredded fiber routed to RESHA-certified processing partners with batch traceability.',
      },
      {
        icon: 'Leaf',
        name: 'New Life',
        description: 'Converted into recycled fiber, ESG-tracked sustainable materials, and circular products.',
      },
    ],
  },
  moksha: {
    title: 'The Moksha Shredder™',
    subtitle: 'On-site. Dignified. Irreversible.',
    description: 'Our proprietary shredding units are installed directly within temple premises. Sacred cloth is processed on-site — never leaving consecrated grounds as intact fabric — preserving ritual completion while preparing the fiber for its next life.',
    specs: [
      { label: 'Capacity', value: '80 kg/day' },
      { label: 'Footprint', value: '1.2m × 0.8m' },
      { label: 'Process', value: 'Dignity-certified' },
      { label: 'Noise', value: '<45 dB' },
    ],
  },
  traceability: {
    title: 'Every Fiber. Fully Traced.',
    description: 'From the temple floor to the recycled product — every batch carries a verifiable chain of custody. Sacred cloth earns a dignified afterlife with full transparency.',
    featured_batch: {
      id: 'RSH-2024-VNS-0147',
      source: 'Kashi Vishwanath Temple Trust, Varanasi, UP',
      collection_date: '12 April 2025',
      shredder: 'MS-007 (Installed: Jan 2025)',
      partner: 'EcoFiber Pvt. Ltd., Kanpur',
      output: '34.2 kg recycled cotton fiber',
      destination: 'Meditation cushion manufacturing, Bengaluru',
      status: 'Delivered & Certified',
    },
  },
  metrics: {
    title: 'The Impact So Far',
    description: 'Pilot-stage numbers from 8 active sites across 3 Indian states',
  },
  network: {
    title: 'Our Growing Network',
    description: 'Active pilot sites, onboarding institutions, and certified processing partners — mapped across India.',
    cta_text: 'Open Full Operations Dashboard →',
  },
  cta: {
    title: 'Bring Dignity to Your Sacred Waste.',
    description: 'Join India\'s first ritual textile circular economy network. Request a pilot Moksha Shredder installation for your institution.',
    button_text: 'Request a Pilot Installation',
    secondary_link: 'Learn about ESG partnerships →',
  },
};

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Puducherry',
];
